// Re-export from generated posts data
// The data is generated by scripts/build-posts.ts before vite build

import { posts, type Post, type PostMeta } from './posts-data'

export type { Post, PostMeta }

export function getAllPosts(): PostMeta[] {
  return posts.map((post) => post.meta)
}

export function getPostBySlug(slug: string): Post | null {
  return posts.find((post) => post.meta.slug === slug) || null
}
