baseURL = 'https://raizawa-blog.pages.dev'
languageCode = 'en-us'
title = 'R-Aizawa Blog'
theme = 'paper'

[services]
  [services.disqus]
    shortname = 'YOUR_DISQUS_SHORTNAME' 

[params]
github = "Xantibody"
zenn = "master_peace_36"
rss = true
name = 'Ryu Aizawa'

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']
